### ISSUE TITLE
Code restart required after installation?

### ISSUE THREAD

**Issue by enekonieto** [gparlakov/scuri-code#32]
After installing plugin `Create spec` command was failing with `schematics not found` error. I followed the path and saw that `~/.config/Code/User/globalStorage/gparlakov.scuri-code/deps` was empty. After closing and reopening Code folder has stuff and command was working.

Sorry, I didn't take the time to test if it replicates.

Code version info:
```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-90-generic
```

**Comment by gparlakov** [comment]
Hi @enekonieto,
Sorry, I took so long to respond. 

It should not require a restart. 

Have you been experiencing similar issues again?

**Comment by enekonieto** [comment]
No, I didn't. I think you can close this issue.
